all: calvino-nanovg.dylan calvino-nanovg-gl.dylan

calvino-nanovg.dylan: calvino-nanovg.intr
	melange -Iext/nanovg/src calvino-nanovg.intr calvino-nanovg.dylan

calvino-nanovg-gl.dylan: calvino-nanovg-gl.intr
	melange -Iext/nanovg/src calvino-nanovg.intr calvino-nanovg.dylan

